"""Deterministic native-size adaptation. Original artwork: Oswarlin @Oswarlin3."""
from pathlib import Path
import argparse,json,hashlib,subprocess,struct,math
from PIL import Image,ImageEnhance
ROOT=Path(__file__).resolve().parents[2]
OUT=ROOT/'graphics/arena/oswarlin'
ART=ROOT/'.arena-dev/art/oswarlin'
NAMES=[('forest','Biome-Forest-V1.jpg',0),('water',None,1),('cave',None,2),('desert','biome-desert-V2.jpg',3),('common','Comun-Battle Arena-V1.jpeg',4),('tallgrass','Biome-Tall grass-V1.jpg',0),('beach','Biome-coast-v2.jpg',3),('base','base arena.jpeg',4),('roxanne','Petra Gym Arena-V1.jpeg',4),('brawly','Marcial Gym Arena-V1.png',4),('wattson','Watsson Gym Arena-V1.png',4),('flannery','Candela Gym Arena-V1.jpeg',4),('norman','Norman Gym Arena-V1.jpeg',4),('winona','Alana Gym Arena-V1.jpeg',4),('tate_liza','Bito & Leti Gym Arena-V1.jpeg',4),('juan','Gemini_Generated_Image_w6uydhw6uydhw6uy.jpeg',4)]
def adapt(im,name):
    im=im.convert('RGB');w,h=im.size
    if name in [n for n,_,_ in NAMES[8:]]:
        xs=[.22,.30,.70,.78];ys=[.21,.30,.65,.77]
        dx=[0,14,226,240];dy=[0,26,145,160]
        result=Image.new('RGB',(240,160))
        for y in range(3):
            for x in range(3):
                cell=im.crop((round(w*xs[x]),round(h*ys[y]),round(w*xs[x+1]),round(h*ys[y+1])))
                result.paste(cell.resize((dx[x+1]-dx[x],dy[y+1]-dy[y]),Image.Resampling.BOX),(dx[x],dy[y]))
        im=result
        if name=='wattson':im=ImageEnhance.Brightness(ImageEnhance.Color(im).enhance(.65)).enhance(.79)
    elif name in ('common','base'):
        box=(.08,.15,.92,.94) if name=='common' else (.02,.13,.98,.96)
        im=im.crop(tuple(round(v*(w if i%2==0 else h)) for i,v in enumerate(box))).resize((240,160),Image.Resampling.BOX)
    else:im=im.resize((240,160),Image.Resampling.BOX)
    return im.quantize(colors=96,dither=Image.Dither.NONE).convert('RGB')
def main():
    p=argparse.ArgumentParser();p.add_argument('--source',type=Path);a=p.parse_args()
    OUT.mkdir(exist_ok=True);ART.mkdir(parents=True,exist_ok=True)
    records=[]
    if a.source:
        badge_source=a.source.parent/'Badges.webp'
        badges=Image.open(badge_source).convert('RGBA')
        badges.save(OUT/'badges-source.png')
        badge_boxes=[(18,18,165,150),(195,15,335,140),(338,8,478,145),(370,165,530,325),(175,155,330,315),(25,330,170,485),(195,355,355,505),(385,340,550,505)]
        for name,filename,biome in NAMES:
            if filename is None:continue
            source=a.source/filename
            adapted=adapt(Image.open(source),name)
            if name in [n for n,_,_ in NAMES[8:]]:
                badge=badges.crop(badge_boxes[[n for n,_,_ in NAMES[8:]].index(name)])
                badge=badge.crop(badge.getbbox());badge.thumbnail((12,12),Image.Resampling.NEAREST)
                adapted.paste(badge,(120-badge.width//2,2),badge)
            adapted.save(OUT/(name+'.png'))
            records.append(dict(name=name,source=filename,sha256=hashlib.sha256(source.read_bytes()).hexdigest(),biome=biome,credit='Oswarlin (@Oswarlin3)',adaptation='native-size reframe and palette conversion'))
        (OUT/'credits.json').write_text(json.dumps(records,indent=2,ensure_ascii=False))
    subprocess.run(['cc','-std=c11','-O2','-I/opt/homebrew/include',str(ROOT/'tools/arena/pack_background.c'),'-L/opt/homebrew/lib','-lpng','-o',str(ART/'pack')],check=True)
    lines=['// Generated by import_oswarlin.py. Attribution: graphics/arena/oswarlin/credits.json.']
    for index,(name,filename,biome) in enumerate(NAMES):
        if filename:
            subprocess.run([str(ART/'pack'),str(OUT/(name+'.png')),str(ART/(name+'.8bpp')),str(ART/(name+'.gbapal')),str(ART/(name+'.bin'))],check=True)
            path='.arena-dev/art/oswarlin/'+name
        else:path='.arena-dev/art/'+('coast' if name=='water' else name)
        # Reserve a matched wet counterpart for every dry color. Nearest-color
        # lookup into a sand-only palette used to flatten floods into brown.
        source=ROOT/path
        raw=source.with_suffix('.8bpp').read_bytes()
        oldpal=struct.unpack('<256H',source.with_suffix('.gbapal').read_bytes())
        rgb=[((c&31)*8,((c>>5)&31)*8,((c>>10)&31)*8) for c in oldpal]
        im=Image.new('RGB',(240,160));im.putdata([rgb[c] for c in raw])
        quant=im.quantize(colors=96,dither=Image.Dither.NONE)
        colors=quant.getpalette();colors += [0]*(288-len(colors));pal=[0]*256
        for i in range(96):
            r,g,b=[v//8 for v in colors[i*3:i*3+3]]
            pal[16+i]=r|(g<<5)|(b<<10)
            r,g,b=[round(v*.74+t*.26) for v,t in zip((r,g,b),(6,17,20))]
            pal[128+i]=r|(g<<5)|(b<<10)
        path='.arena-dev/art/oswarlin/'+name
        packed=ROOT/path
        packed.with_suffix('.8bpp').write_bytes(bytes(c+16 for c in quant.tobytes()))
        packed.with_suffix('.gbapal').write_bytes(struct.pack('<256H',*pal))
        lines += [f'static const u32 sStage{index}Tiles[]=INCBIN_U32("{path}.8bpp");',f'static const u16 sStage{index}Pal[]=INCBIN_U16("{path}.gbapal");']
    lines += ['const u32 *const gArenaStageTiles[]={'+','.join(f'sStage{i}Tiles' for i in range(16))+'};','const u16 *const gArenaStagePalettes[]={'+','.join(f'sStage{i}Pal' for i in range(16))+'};']
    (OUT/'stages.inc').write_text('\n'.join(lines)+'\n')
    flood=bytearray()
    for name,filename,biome in NAMES:
        path=ART/name
        palette=struct.unpack('<256H',path.with_suffix('.gbapal').read_bytes())
        rgb=[(c&31,(c>>5)&31,(c>>10)&31) for c in palette]
        def nearest(v):return min(range(16,240),key=lambda i:sum((x-y)**2 for x,y in zip(rgb[i],v)))
        remap=list(range(256))
        for i in range(240,247):remap[i]=nearest(rgb[i])
        shade=[i+112 if 16<=i<112 else i for i in range(256)]
        raw=path.with_suffix('.8bpp').read_bytes()
        flood.extend(bytes(remap[c] for c in raw));flood.extend(bytes(shade[c] for c in raw))
    (OUT/'flood.8bpp').write_bytes(flood)
    # Pixel-granular shared shoreline: the renderer and collision/electricity
    # query exactly this field, never a visible 8x8 tile rectangle.
    heights=bytearray()
    for y in range(160):
        for x in range(240):
            if not (16<=x<224 and 40<=y<136):
                heights.append(255);continue
            dx=(x-120+3*math.sin(y*.11))/102
            dy=(y-88+2*math.sin(x*.075))/46
            h=12+38*(dx**4+dy**4)+3*math.sin(x*.10+y*.08)+2*math.cos(y*.2-x*.06)
            for cx,cy in ((48,112),(192,56)):
                island=((x-cx)/24)**2+((y-cy)/14)**2
                h=max(h,68-30*island)
            heights.append(max(0,min(254,round(h))))
    (OUT/'water-height.bin').write_bytes(heights)
    tiled=bytearray();bounds=bytearray();mask=bytearray()
    for ty in range(20):
        for tx in range(30):
            tile=bytes(heights[(ty*8+y)*240+tx*8+x] for y in range(8) for x in range(8))
            tiled.extend(tile);bounds.extend((min(tile),max(tile)))
            for p,h in enumerate(tile):
                depth=48-h;x=tx*8+(p&7);y=ty*8+(p>>3)
                mask.append(255 if depth>0 and (depth>=3 or ((x+y)&3)<depth) else 0)
    (OUT/'water-height-tiled.bin').write_bytes(tiled)
    (OUT/'water-height-bounds.bin').write_bytes(bounds)
    (OUT/'water-full-mask.bin').write_bytes(mask)
    (ROOT/'src/arena_stage_art.c').touch()
if __name__=='__main__':main()
